[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位
ruleset=国外流量,clash-classic:https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/ip138.list
ruleset=myTV SUPER,clash-classic:https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/pixman.list
ruleset=myTV SUPER,clash-classic:https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/pixman-ntp.list
ruleset=奥视澳门,clash-classic:https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/tmd.list
ruleset=4gtv,clash-classic:https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/4gtv.list
ruleset=内网穿透,https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/IntranetIP.list
;阿里云IP段
ruleset=国内流量,https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/ChinaCompanyIp.list
;国内IP段
;ruleset=国内流量,https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/ChinaIp.list
ruleset=国内流量,[]GEOIP,CN
ruleset=YouTube,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
ruleset=Telegram,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list
ruleset=OpenAI,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=Gemini,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=AppleIntelligence,clash-classic:https://raw.githubusercontent.com/ddgksf2013/Filter/refs/heads/master/AppleIntelligence.list
ruleset=TikTok,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=Google,clash-classic:https://raw.githubusercontent.com/litiande/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=国外流量,clash-classic:https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/ProxyGFWlist1.list
ruleset=漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=国外流量`select`[]自动选择`[]手动切换`[]DIRECT`[]香港节点`[]台湾节点`[]新加坡节点`[]马来西亚节点`[]日本节点`[]美国节点`[]韩国节点
custom_proxy_group=国内流量`select`[]DIRECT`[]国外流量`[]自动选择
custom_proxy_group=手动切换`select`.*
custom_proxy_group=自动选择`url-test`(^(?!.*x(?:[2-9]|[1-9][0-9]))(?=.*(?:港|香港|HongKong|HK|Hong Kong|台|新北|彰化|TW|Taiwan|新加坡|坡|狮城|SG|Singapore|马来西亚|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|美|U.S.A|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States|USA Lan Vegas|KR|Korea|韩国|KOR|首尔|韩|韓)).*$)`https://i.ytimg.com/generate_204`60,150
custom_proxy_group=myTV SUPER`select`(.*(港|香港|HongKong|HK|Hong Kong).*)
custom_proxy_group=奥视澳门`select`(.*(澳门|mo|MO|Macao|macao|港|香港|HongKong|HK|Hong Kong).*)
custom_proxy_group=4gtv`select`(.*(台湾).*)
custom_proxy_group=内网穿透`select`(.*(广东河源电信-IPv4|广东广州电信-IPv6).*)
custom_proxy_group=漏网之鱼`select`[]国外流量`[]自动选择`[]DIRECT`[]手动切换
custom_proxy_group=YouTube`select`.*
custom_proxy_group=Telegram`select`[]香港节点`[]台湾节点`[]新加坡节点`[]马来西亚节点`[]日本节点`[]美国节点`[]韩国节点
custom_proxy_group=TikTok`select`[]台湾节点`[]新加坡节点`[]马来西亚节点`[]日本节点`[]美国节点`[]韩国节点
custom_proxy_group=OpenAI`select`[]台湾节点`[]新加坡节点`[]马来西亚节点`[]日本节点`[]美国节点`[]韩国节点
custom_proxy_group=Gemini`select`[]香港节点`[]台湾节点`[]新加坡节点`[]马来西亚节点`[]日本节点`[]美国节点`[]韩国节点
custom_proxy_group=AppleIntelligence`select`[]台湾节点`[]新加坡节点`[]马来西亚节点`[]日本节点`[]美国节点`[]韩国节点
custom_proxy_group=Google`select`.*
custom_proxy_group=中国大陆节点`select`(.*(广东河源电信-IPv4|广东广州电信-IPv6).*)
custom_proxy_group=香港节点`select`(港|香港|HongKong|HK|Hong Kong)
custom_proxy_group=台湾节点`select`(台|新北|彰化|TW|Taiwan)
custom_proxy_group=新加坡节点`select`(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=马来西亚节点`select`(马来西亚)
custom_proxy_group=日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)
custom_proxy_group=美国节点`select`(美|U.S.A|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States)
custom_proxy_group=韩国节点`select`(KR|Korea|韩国|KOR|首尔|韩|韓)
enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
