[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：支持
;增强国外GFW：支持

;设置规则标志位

ruleset=🚄 内网穿透,clash-classic:https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/4gtv.list
ruleset=🚄 内网穿透,https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/IntranetIP.list
;阿里云IP段
ruleset=🚄 内网穿透,https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/ChinaCompanyIp.list
;国内IP段
;ruleset=🚄 内网穿透,https://raw.githubusercontent.com/litiande03/Clash/refs/heads/master/rules/ChinaIp.list
ruleset=🚄 内网穿透,[]GEOIP,CN

ruleset=🚄 内网穿透,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list

ruleset=🚄 内网穿透,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list

ruleset=🚄 内网穿透,clash-classic:https://raw.githubusercontent.com/ddgksf2013/Filter/refs/heads/master/AppleIntelligence.list

ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚄 内网穿透`select`(.*(广东河源电信-IPv4|广东广州电信-IPv6).*)

custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
